select * from employees;
select * from DEPARTMENTS;
select * from LOCATIONS;

select DEPARTMENT_NAME from DEPARTMENTS;
select PHONE_NUMBER from EMPLOYEES;

select DEPARTMENT_ID, DEPARTMENT_NAME from DEPARTMENTS;

select EMPLOYEES.FIRST_NAME,DEPARTMENTS.DEPARTMENT_NAME from DEPARTMENTS, EMPLOYEES;
select distinct (SALARY) from EMPLOYEES;